### ISSUE TITLE
Authorization error while validating the yaml file

### ISSUE THREAD

**Issue by micheleissa** [tomaustin700/YAML-Pipeline-Validator-VS-Code-Extension#1]
Hello,
I'm getting this error regarding the variable group while trying to validate the pipeline. Is there a way to authenticate so Visual Studio Code can access whatever it needs to access and pass it down to the validation api.

![image](https://user-images.githubusercontent.com/16201881/94826252-bb913700-03cc-11eb-83c9-bb44d5f15d43.png)

Thanks

**Comment by tomaustin700** [comment]
Hi @micheleissa
Can you provide me with some example yaml so I can investigate this? 
Thanks

**Comment by tomaustin700** [comment]
I've been able to duplicate it with the following yaml, I will investigate however I'm not sure I'll be able to do anything to resolve this due to the way the pipeline is validated. I'll investigate.
```yaml
trigger: 
- main

variables:
- group: my-variable-group
```

**Comment by tomaustin700** [comment]
Hi @micheleissa, I've added some settings which should help your out. Please see #2. Let me know if you need anymore assistance. Thanks for raising this.

**Comment by micheleissa** [comment]
@tomaustin700  gr8 I will try and let you know.
