### ISSUE TITLE
What is the URL (https://yamlpipelinesvalidatordev.azurewebsites.net/api/validate) doing ?

### ISSUE THREAD

**Issue by osho1278** [tomaustin700/YAML-Pipeline-Validator-VS-Code-Extension#17]
For security reasons a high level understanding is needed about the api.

https://yamlpipelinesvalidatordev.azurewebsites.net/api/validate

Please point to any GIT repo

**Comment by tomaustin700** [comment]
Hi @osho1278,
Please see ```Validate``` method in this file:
https://github.com/tomaustin700/yamlpipelinesvalidator.dev/blob/master/Function/API/API/API.cs

Thanks
