### ISSUE TITLE
Validation is broken for any pipeline?

### ISSUE THREAD

**Issue by dsantunes** [tomaustin700/YAML-Pipeline-Validator-VS-Code-Extension#20]
**Describe the bug**
No matter what state the yaml is in, the pipeline validator says the Pipeline is valid.
This started a couple weeks ago maybe. Wondering if there were any API changes or something which broke the validation.

**To Reproduce**
Take any existing yaml really

**Expected behavior**
Basic syntax issues should be picked up

**Screenshots**

**Example yaml
Any

**Additional context**
VSCode 1.82.3

**Comment by adjiap** [comment]
Same, I see the same issue, it'd be nice if it'll be fixed. I assume there's a change in API at AzDo side.

**Comment by tomaustin700** [comment]
@dsantunes @adjiap  - Will try take a look at this over the next few days! Thanks for reporting

**Comment by tomaustin700** [comment]
This should now be resolved

**Comment by dsantunes** [comment]
Confirmed, thanks!
