### ISSUE TITLE
Extension indicate valid yaml but it is not

### ISSUE THREAD

**Issue by micheleissa** [tomaustin700/YAML-Pipeline-Validator-VS-Code-Extension#6]
**Describe the bug**
I'm trying to test the extension after the latest changes and intentionally have an incorrect indentation in one of script tasks in pipeline but when executing the extension via the shortcut it indicates Valid pipeline but the same pipeline on AZDO is not valid and shows the exact error line.

**To Reproduce**
Just put an incorrect indentation in a task e.g. bash task like below

**Expected behavior**
Minimum a generic error message or a detailed one because the API indicates the error and line number.

**Screenshots**
Error message from AZDO
![image](https://user-images.githubusercontent.com/16201881/95244103-27154300-07d7-11eb-8fa1-4e2ced570e0e.png)

Incorrect message from extension 
![image](https://user-images.githubusercontent.com/16201881/95244561-c20e1d00-07d7-11eb-8a0d-f4d682efbdcd.png)

**Example yaml
```
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
    echo 'Hello world'
```

**Additional context**

**Comment by micheleissa** [comment]
@tomaustin700 thank you again for such prompt responses to the issues.

**Comment by tomaustin700** [comment]
Hi @micheleissa, I'll take a look at this tomorrow. If you put the yaml into https://yamlpipelinesvalidator.dev/ does it state it's valid?

**Comment by micheleissa** [comment]
> Hi @micheleissa, I'll take a look at this tomorrow. If you put the yaml into https://yamlpipelinesvalidator.dev/ does it state it's valid?

Unfortunately my work organization's proxy/firewall causing the site not to behave correctly so when I click validate nothing happens.
I've forked the code and I see that the ```Valid Pipeline``` message shows up no matter what happens inside the call, I think the result should be inspected to check if anything comes back then based on it display the proper message.

**Comment by tomaustin700** [comment]
Hi @micheleissa, 
I have detected an issue where if any of  ```yamlpipelinesvalidator.builddefinitionid``` , ```yamlpipelinesvalidator.projecturl``` and ```yamlpipelinesvalidator.pat``` are invalid this could occur. I will patch this in the API so that it returns the correct error and add some handling to the extension that informs the user of what the problem is.

**Comment by tomaustin700** [comment]
Updated API to report errors better. This seems to occur when a setting is invalid and message should now inform of that.
